Prompt for consent
Weble/ZohoClient pull request #22
Opened 2021-07-12 16:55 UTC by mogilvie

Books API permits configuration to prompt the user for consent to access the requested Scopes.
Pull request provides this function in ZohoClient

2021-07-12 19:59 UTC, Skullbock requested changes

2021-07-12 19:59 UTC, Skullbock commented on src/OAuthClient.php
> +        dump($this);
Can you remove the dump? 😜

2021-07-12 21:44 UTC, mogilvie commented on src/OAuthClient.php
> +        dump($this);
Done, thanks.

2021-07-13 06:30 UTC, merged

2021-07-13 06:30 UTC, Skullbock commented
Thanks to you!